# Generated by Django 4.2.4 on 2023-08-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_details', '0002_cart_cart_items_order_items_delete_color_delete_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_items',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
