# Generated by Django 4.2.4 on 2023-08-30 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0029_remove_my_order_product'),
        ('product_details', '0004_cart_items_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_items',
            name='product',
        ),
        migrations.AddField(
            model_name='order_items',
            name='variant',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='admin_page.variants'),
            preserve_default=False,
        ),
    ]
