# Generated by Django 4.2.3 on 2023-08-30 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0029_remove_my_order_product'),
        ('product_details', '0005_remove_order_items_product_order_items_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_items',
            name='variant',
        ),
        migrations.AddField(
            model_name='order_items',
            name='product',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='admin_page.product'),
            preserve_default=False,
        ),
    ]
