# Generated by Django 4.2.4 on 2023-09-01 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0030_my_order_order_status'),
        ('product_details', '0008_remove_order_items_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_items',
            name='product',
        ),
        migrations.AddField(
            model_name='order_items',
            name='variant',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='admin_page.variants'),
            preserve_default=False,
        ),
    ]
