# Generated by Django 4.2.3 on 2023-08-01 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_page.categories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(),
        ),
    ]
