# Generated by Django 4.2.3 on 2023-08-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0009_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_price',
            field=models.IntegerField(),
        ),
    ]
