# Generated by Django 4.2.3 on 2023-08-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0013_alter_product_discount_alter_product_offer_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
