# Generated by Django 4.2.4 on 2023-08-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_details', '0001_initial'),
        ('admin_page', '0016_alter_product_discount_alter_product_offer_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(max_length=20, to='product_details.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(max_length=10, to='product_details.color'),
        ),
    ]
