# Generated by Django 4.2.4 on 2023-08-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_details', '0001_initial'),
        ('admin_page', '0017_remove_product_color_remove_product_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(max_length=20, to='product_details.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(max_length=10, to='product_details.size'),
        ),
    ]
