# Generated by Django 4.2.4 on 2023-08-16 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0020_my_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_order',
            name='quantity',
        ),
    ]
