# Generated by Django 4.2.4 on 2023-08-16 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_pages', '0007_address_user'),
        ('admin_page', '0021_remove_my_order_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='my_order',
            name='address',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='profile_pages.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='my_order',
            name='payment_method',
            field=models.CharField(default=6, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(to='admin_page.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='admin_page.size'),
        ),
    ]
