# Generated by Django 4.2.4 on 2023-08-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0023_alter_size_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='offer_price',
        ),
        migrations.AddField(
            model_name='product',
            name='discription',
            field=models.CharField(default=5, max_length=150),
            preserve_default=False,
        ),
    ]
