# Generated by Django 4.2.4 on 2023-08-19 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0024_remove_product_offer_price_product_discription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='total_quantity',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('price', models.IntegerField()),
                ('discription', models.CharField(max_length=150)),
                ('quantity', models.PositiveIntegerField()),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('color', models.ManyToManyField(to='admin_page.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_page.product')),
                ('size', models.ManyToManyField(to='admin_page.size')),
            ],
        ),
    ]
