# Generated by Django 4.2.4 on 2023-08-19 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0025_remove_product_color_remove_product_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='color',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='size',
        ),
        migrations.AddField(
            model_name='variants',
            name='color',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='admin_page.color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variants',
            name='size',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='admin_page.size'),
            preserve_default=False,
        ),
    ]
