# Generated by Django 4.2.4 on 2023-08-19 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0026_remove_variants_color_remove_variants_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_quantity',
        ),
    ]
