# Generated by Django 4.2.4 on 2023-08-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0027_remove_product_total_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
