# Generated by Django 4.2.4 on 2023-08-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0029_remove_my_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
