# Generated by Django 4.2.4 on 2023-09-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0030_my_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='discription',
            field=models.CharField(max_length=500),
        ),
    ]
