# Generated by Django 4.2.4 on 2023-09-12 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0035_remove_wishlist_products_wishlist_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product',
            new_name='products',
        ),
    ]
