# Generated by Django 4.2.4 on 2023-09-12 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0036_rename_product_wishlist_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='products',
        ),
    ]
