# Generated by Django 4.2.4 on 2023-09-12 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0039_alter_wishlist_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='variant',
        ),
    ]
