# Generated by Django 4.2.3 on 2023-07-25 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_user_details_otp_user_details_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='uid',
        ),
    ]
