# Generated by Django 4.2.3 on 2023-07-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_user_details_otp_remove_user_details_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
