# Generated by Django 4.2.4 on 2023-08-07 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_user_details_age_user_details_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='gender',
        ),
    ]
