# Generated by Django 4.2.4 on 2023-08-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_user_details_age_remove_user_details_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
