# Generated by Django 4.2.3 on 2023-08-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_user_details_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='age',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default=3, max_length=10),
            preserve_default=False,
        ),
    ]
