# Generated by Django 4.2.4 on 2023-08-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_information',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
