# Generated by Django 4.2.4 on 2023-08-07 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_pages', '0002_alter_personal_information_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personal_Information',
        ),
    ]
