# Generated by Django 4.2.4 on 2023-08-16 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_user_details_age_remove_user_details_gender'),
        ('profile_pages', '0006_alter_address_alter_phone_alter_address_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='home.user_details'),
            preserve_default=False,
        ),
    ]
