# Generated by Django 4.2.4 on 2023-08-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_pages', '0007_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='alter_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
