# Generated by Django 4.2.4 on 2023-09-12 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_pages', '0010_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
